# Generated by Django 2.0.7 on 2018-07-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouns', models.SlugField(blank=True)),
                ('verbs', models.SlugField(blank=True)),
                ('adj', models.SlugField(blank=True)),
                ('prep', models.SlugField(blank=True)),
                ('verbs_i', models.SlugField(blank=True)),
                ('adv', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transliterate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('src', models.CharField(choices=[('0', 'UK IPA'), ('1', 'US IPA'), ('2', 'Klattese'), ('3', 'SAMPA'), ('4', 'ARPABET')], max_length=2)),
                ('dst', models.CharField(choices=[('0', 'UK IPA'), ('1', 'US IPA'), ('2', 'Klattese'), ('3', 'SAMPA'), ('4', 'ARPABET')], max_length=2)),
            ],
        ),
    ]
