# Generated by Django 2.1.5 on 2019-01-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentround',
            old_name='prev_word1',
            new_name='word1',
        ),
        migrations.RenameField(
            model_name='currentround',
            old_name='prev_word2',
            new_name='word2',
        ),
    ]
