# Generated by Django 2.1.5 on 2019-01-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0002_auto_20190120_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentround',
            name='answer',
            field=models.CharField(default='bla', max_length=100),
            preserve_default=False,
        ),
    ]
