# Generated by Django 2.1.5 on 2019-01-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0003_currentround_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentround',
            name='question_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
